name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run custom script
      run: npm run custom-script
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: /var/www/nextjs-app/
        remote_host: ec2-18-134-246-47.eu-west-2.compute.amazonaws.com
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Set Environment Variable
      run: echo "REMOTE_JSON_PATH=$(ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_SERVER }} 'readlink -f /var/www/nextjs-app/output.json')" >> $GITHUB_ENV