name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run custom script
      run: npm run custom-script
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./output.json
        remote_path: /var/www/nextjs-app/
        remote_host: ec2-13-43-55-102.eu-west-2.compute.amazonaws.com
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ec2-13-43-55-102.eu-west-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: export OUTPUT_JSON_PATH=$(readlink -f /var/www/nextjs-app/output.json)

  
  